2024-11-13 08:48:44,606 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 362, in rate
    avg_ratings = rating_service.get_average_rating(dataset_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 257, in get_average_rating
    raise e
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 08:52:51,812 - app.modules.dataset.services - ERROR - Error al obtener calificaciones promedio
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 08:52:51,813 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 362, in rate
    avg_ratings = rating_service.get_average_rating(dataset_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 257, in get_average_rating
    raise e
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 09:08:27,352 - app.modules.dataset.services - ERROR - Error al obtener calificaciones promedio
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 09:08:27,354 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 362, in rate
    avg_ratings = rating_service.get_average_rating(dataset_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 257, in get_average_rating
    raise e
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 09:23:17,077 - app.modules.dataset.services - ERROR - Error al obtener calificaciones promedio
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 09:23:17,079 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 362, in rate
    avg_ratings = rating_service.get_average_rating(dataset_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 257, in get_average_rating
    raise e
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 09:56:52,640 - app.modules.dataset.services - ERROR - Error al obtener calificaciones promedio
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 09:56:52,642 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 362, in rate
    avg_ratings = rating_service.get_average_rating(dataset_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 257, in get_average_rating
    raise e
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 09:59:26,754 - app.modules.dataset.services - ERROR - Error al obtener calificaciones promedio
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 09:59:26,756 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 362, in rate
    avg_ratings = rating_service.get_average_rating(dataset_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 257, in get_average_rating
    raise e
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 10:00:45,278 - app.modules.dataset.services - ERROR - Error al obtener calificaciones promedio
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 242, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
                               ^^^^^^
NameError: name 'Rating' is not defined
2024-11-13 10:00:45,280 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 362, in rate
    avg_ratings = rating_service.get_average_rating(dataset_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 259, in get_average_rating
    raise e
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 242, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
                               ^^^^^^
NameError: name 'Rating' is not defined
2024-11-13 10:03:44,553 - app.modules.dataset.services - ERROR - Error al obtener calificaciones promedio
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 10:03:44,554 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 362, in rate
    avg_ratings = rating_service.get_average_rating(dataset_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 257, in get_average_rating
    raise e
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 10:04:49,025 - app.modules.dataset.services - ERROR - Error al obtener calificaciones promedio
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 242, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
                               ^^^^^^
NameError: name 'Rating' is not defined
2024-11-13 10:04:49,028 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 362, in rate
    avg_ratings = rating_service.get_average_rating(dataset_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 259, in get_average_rating
    raise e
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 242, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
                               ^^^^^^
NameError: name 'Rating' is not defined
