2024-11-12 23:45:27,884 - app.modules.dataset.services - ERROR - Error al obtener calificaciones promedio
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-12 23:45:27,885 - app.modules.dataset.routes - ERROR - Error al obtener las calificaciones del dataset
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 292, in get_ratings
    avg_ratings = rating_service.get_average_rating(dataset_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 257, in get_average_rating
    raise e
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-12 23:45:42,365 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 315, in rate
    rating = rating_service.add_rating(user_id, dataset_id, quality, size, usability)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 236, in add_rating
    return self.repository.add_rating(dataset_id=dataset_id, user_id=user_id, quality=quality, size=size, usability=usability)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/repositories.py", line 144, in add_rating
    total = (quality + size + usability) / 3.0
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'float'
2024-11-12 23:49:21,763 - app.modules.dataset.services - ERROR - Error al obtener calificaciones promedio
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-12 23:49:21,764 - app.modules.dataset.routes - ERROR - Error al obtener las calificaciones del dataset
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 292, in get_ratings
    avg_ratings = rating_service.get_average_rating(dataset_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 257, in get_average_rating
    raise e
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 240, in get_average_rating
    ratings = db.session.query(Rating).filter_by(dataset_id=dataset_id).all()
              ^^
NameError: name 'db' is not defined
2024-11-13 00:08:32,123 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 322, in rate
    rating = rating_service.add_rating(user_id, dataset_id, quality, size, usability)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 236, in add_rating
    return self.repository.add_rating(dataset_id=dataset_id, user_id=user_id, quality=quality, size=size, usability=usability)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/repositories.py", line 144, in add_rating
    total = (quality + size + usability) / 3.0
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'float'
2024-11-13 00:19:14,539 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 322, in rate
    rating = rating_service.add_rating(user_id, dataset_id, quality, size, usability)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 236, in add_rating
    return self.repository.add_rating(dataset_id=dataset_id, user_id=user_id, quality=quality, size=size, usability=usability)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/repositories.py", line 144, in add_rating
    total = (quality + size + usability) / 3.0
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'float'
2024-11-13 00:24:57,882 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 322, in rate
    rating = rating_service.add_rating(user_id, dataset_id, quality, size, usability)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 236, in add_rating
    return self.repository.add_rating(dataset_id=dataset_id, user_id=user_id, quality=quality, size=size, usability=usability)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/repositories.py", line 144, in add_rating
    total = (quality + size + usability) / 3.0
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'float'
2024-11-13 00:31:05,230 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 322, in rate
    rating = rating_service.add_rating(user_id, dataset_id, quality, size, usability)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 236, in add_rating
    return self.repository.add_rating(dataset_id=dataset_id, user_id=user_id, quality=quality, size=size, usability=usability)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/repositories.py", line 144, in add_rating
    total = (quality + size + usability) / 3.0
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'float'
2024-11-13 00:46:54,309 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 322, in rate
    rating = rating_service.add_rating(user_id, dataset_id, quality, size, usability)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 236, in add_rating
    return self.repository.add_rating(dataset_id=dataset_id, user_id=user_id, quality=quality, size=size, usability=usability)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/repositories.py", line 144, in add_rating
    total = (quality + size + usability) / 3.0
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'float'
2024-11-13 00:49:34,786 - app.modules.dataset.routes - ERROR - Error al agregar la calificación
Traceback (most recent call last):
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/routes.py", line 322, in rate
    rating = rating_service.add_rating(user_id, dataset_id, quality, size, usability)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/services.py", line 236, in add_rating
    return self.repository.add_rating(dataset_id=dataset_id, user_id=user_id, quality=quality, size=size, usability=usability)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Escritorio/berenjena-hub/app/modules/dataset/repositories.py", line 144, in add_rating
    total = (quality + size + usability) / 3.0
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'float'
