2024-12-03 23:11:27,608 - app.modules.dashboard.tests.test_unit - ERROR - Exception on /dashboard/ [GET]
Traceback (most recent call last):
  File "/home/sheng/berenjena-hub/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sheng/berenjena-hub/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sheng/berenjena-hub/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sheng/berenjena-hub/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sheng/berenjena-hub/app/modules/dashboard/routes.py", line 33, in index
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/home/sheng/berenjena-hub/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sheng/berenjena-hub/venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sheng/berenjena-hub/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/sheng/berenjena-hub/venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/sheng/berenjena-hub/app/modules/dashboard/templates/dashboard.html", line 1, in top-level template code
    {% extends "base_template.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sheng/berenjena-hub/app/templates/base_template.html", line 65, in top-level template code
    <a class="sidebar-link" href="{{ url_for('explore.index') }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sheng/berenjena-hub/venv/lib/python3.12/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sheng/berenjena-hub/venv/lib/python3.12/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sheng/berenjena-hub/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'explore.index'. Did you mean 'public.index' instead?
